pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
println("20250122b-settings.gradle-01-----------------settings.gradle----------------------------------------->")
rootProject.name = "gpupixel"
include ':gpupixel'
